/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wangkm_video_tools_utils_FFmpegUtils */

#ifndef _Included_com_wangkm_video_tools_utils_FFmpegUtils
#define _Included_com_wangkm_video_tools_utils_FFmpegUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wangkm_video_tools_utils_FFmpegUtils
 * Method:    stringNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wangkm_video_tools_utils_FFmpegUtils_stringNative
  (JNIEnv *, jclass);

/*
 * Class:     com_wangkm_video_tools_utils_FFmpegUtils
 * Method:    stringJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wangkm_video_tools_utils_FFmpegUtils_stringJni
  (JNIEnv *, jclass);

/*
 * Class:     com_wangkm_video_tools_utils_FFmpegUtils
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wangkm_video_tools_utils_FFmpegUtils_decode
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_wangkm_video_tools_utils_FFmpegUtils
 * Method:    stream
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wangkm_video_tools_utils_FFmpegUtils_stream
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
